import type { Metadata } from "next";

import { Roboto } from "next/font/google"; // Importamos Roboto
import "./globals.css";


export const metadata: Metadata = {
  title: "MISTALENTOS",
  description: "Generated by create next app",
};
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"], // Roboto tiene muchos pesos útiles
  variable: "--font-roboto",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} font-sans antialiased`}
      >
        {children} 
      </body>
    </html>
  );
}